swagger: "2.0"
info:
  title: "API Gatewayテスト"
  description: "Access-Tokenヘッダーの値を返すAPI"
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-endpoints:
  - name: "ignore cors"
    allowCors: True
paths:
  /hello:
    # プリフライトリクエストで使用
    options:
      summary: "corsをパスするために設定"
      # operationIdは何でもOK(ログで識別しやすくするためのID?)
      operationId: corsHello
      x-google-backend:
        address: "https://backend-demo-747dpngw3q-an.a.run.app/hello"
      responses:
        200:
          description: "成功"
    get:
      summary: "Access-Tokenヘッダーの値を返す"
      # operationIdは何でもOK(ログで識別しやすくするためのID?)
      operationId: hello
      x-google-backend:
        # Cloud Run(API本体)のURL
        address: "https://backend-demo-747dpngw3q-an.a.run.app/hello"
      responses:
        "200":
          description: "成功"
          schema:
            type: object
            properties:
              token: { type: string, example: "アクセストークン" }