swagger: "2.0"
info:
  title: "Backend Demo"
  description: "バックエンドAPIのデモ"
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
tags:
  - name: users
    description: "ユーザーに関する情報"
x-google-endpoints:
  - name: "ignore cors"
    allowCors: True
securityDefinitions:
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
    x-google-audiences: "811974289373-2hp30dkitujdqh6402ckibg442fj94ph.apps.googleusercontent.com"
  firebase:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://securetoken.google.com/api-gateway-demo-404010"
    x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
    x-google-audiences: "api-gateway-demo-404010"
paths:
  /users/me:
    # プリフライトリクエストで使用
    options:
      tags:
        - users
      summary: ""
      operationId: corsMe
      x-google-backend:
        address: "https://backend-demo-747dpngw3q-an.a.run.app/users/me"
      responses:
        200:
          description: "成功"
          schema:
            type: object
            properties:
              name: { type: string, example: "ユーザー名" }
              email: { type: string, example: "Emailアドレス" }
    get:
      tags:
        - users
      summary: "自身の情報を取得"
      security:
        - google_id_token: []
        - firebase: []
      operationId: me
      x-google-backend:
        address: "https://backend-demo-747dpngw3q-an.a.run.app/users/me"
      responses:
        "200":
          description: "成功"
          schema:
            type: object
            properties:
              name: { type: string, example: "ユーザー名" }
              email: { type: string, example: "Emailアドレス" }
