// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend-demo/ent/payment"
	"backend-demo/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (pu *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetEventID sets the "event_id" field.
func (pu *PaymentUpdate) SetEventID(i int) *PaymentUpdate {
	pu.mutation.ResetEventID()
	pu.mutation.SetEventID(i)
	return pu
}

// AddEventID adds i to the "event_id" field.
func (pu *PaymentUpdate) AddEventID(i int) *PaymentUpdate {
	pu.mutation.AddEventID(i)
	return pu
}

// SetAmount sets the "amount" field.
func (pu *PaymentUpdate) SetAmount(i int) *PaymentUpdate {
	pu.mutation.ResetAmount()
	pu.mutation.SetAmount(i)
	return pu
}

// AddAmount adds i to the "amount" field.
func (pu *PaymentUpdate) AddAmount(i int) *PaymentUpdate {
	pu.mutation.AddAmount(i)
	return pu
}

// SetPaidBy sets the "paid_by" field.
func (pu *PaymentUpdate) SetPaidBy(i int) *PaymentUpdate {
	pu.mutation.ResetPaidBy()
	pu.mutation.SetPaidBy(i)
	return pu
}

// AddPaidBy adds i to the "paid_by" field.
func (pu *PaymentUpdate) AddPaidBy(i int) *PaymentUpdate {
	pu.mutation.AddPaidBy(i)
	return pu
}

// SetPaidTo sets the "paid_to" field.
func (pu *PaymentUpdate) SetPaidTo(i int) *PaymentUpdate {
	pu.mutation.ResetPaidTo()
	pu.mutation.SetPaidTo(i)
	return pu
}

// AddPaidTo adds i to the "paid_to" field.
func (pu *PaymentUpdate) AddPaidTo(i int) *PaymentUpdate {
	pu.mutation.AddPaidTo(i)
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *PaymentUpdate) SetUpdatedAt(t time.Time) *PaymentUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetDeletedAt sets the "deleted_at" field.
func (pu *PaymentUpdate) SetDeletedAt(t time.Time) *PaymentUpdate {
	pu.mutation.SetDeletedAt(t)
	return pu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableDeletedAt(t *time.Time) *PaymentUpdate {
	if t != nil {
		pu.SetDeletedAt(*t)
	}
	return pu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (pu *PaymentUpdate) ClearDeletedAt() *PaymentUpdate {
	pu.mutation.ClearDeletedAt()
	return pu
}

// Mutation returns the PaymentMutation object of the builder.
func (pu *PaymentUpdate) Mutation() *PaymentMutation {
	return pu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PaymentUpdate) Save(ctx context.Context) (int, error) {
	pu.defaults()
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PaymentUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PaymentUpdate) defaults() {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		v := payment.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
}

func (pu *PaymentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.EventID(); ok {
		_spec.SetField(payment.FieldEventID, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedEventID(); ok {
		_spec.AddField(payment.FieldEventID, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := pu.mutation.PaidBy(); ok {
		_spec.SetField(payment.FieldPaidBy, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedPaidBy(); ok {
		_spec.AddField(payment.FieldPaidBy, field.TypeInt, value)
	}
	if value, ok := pu.mutation.PaidTo(); ok {
		_spec.SetField(payment.FieldPaidTo, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedPaidTo(); ok {
		_spec.AddField(payment.FieldPaidTo, field.TypeInt, value)
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.DeletedAt(); ok {
		_spec.SetField(payment.FieldDeletedAt, field.TypeTime, value)
	}
	if pu.mutation.DeletedAtCleared() {
		_spec.ClearField(payment.FieldDeletedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetEventID sets the "event_id" field.
func (puo *PaymentUpdateOne) SetEventID(i int) *PaymentUpdateOne {
	puo.mutation.ResetEventID()
	puo.mutation.SetEventID(i)
	return puo
}

// AddEventID adds i to the "event_id" field.
func (puo *PaymentUpdateOne) AddEventID(i int) *PaymentUpdateOne {
	puo.mutation.AddEventID(i)
	return puo
}

// SetAmount sets the "amount" field.
func (puo *PaymentUpdateOne) SetAmount(i int) *PaymentUpdateOne {
	puo.mutation.ResetAmount()
	puo.mutation.SetAmount(i)
	return puo
}

// AddAmount adds i to the "amount" field.
func (puo *PaymentUpdateOne) AddAmount(i int) *PaymentUpdateOne {
	puo.mutation.AddAmount(i)
	return puo
}

// SetPaidBy sets the "paid_by" field.
func (puo *PaymentUpdateOne) SetPaidBy(i int) *PaymentUpdateOne {
	puo.mutation.ResetPaidBy()
	puo.mutation.SetPaidBy(i)
	return puo
}

// AddPaidBy adds i to the "paid_by" field.
func (puo *PaymentUpdateOne) AddPaidBy(i int) *PaymentUpdateOne {
	puo.mutation.AddPaidBy(i)
	return puo
}

// SetPaidTo sets the "paid_to" field.
func (puo *PaymentUpdateOne) SetPaidTo(i int) *PaymentUpdateOne {
	puo.mutation.ResetPaidTo()
	puo.mutation.SetPaidTo(i)
	return puo
}

// AddPaidTo adds i to the "paid_to" field.
func (puo *PaymentUpdateOne) AddPaidTo(i int) *PaymentUpdateOne {
	puo.mutation.AddPaidTo(i)
	return puo
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *PaymentUpdateOne) SetUpdatedAt(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetDeletedAt sets the "deleted_at" field.
func (puo *PaymentUpdateOne) SetDeletedAt(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetDeletedAt(t)
	return puo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableDeletedAt(t *time.Time) *PaymentUpdateOne {
	if t != nil {
		puo.SetDeletedAt(*t)
	}
	return puo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (puo *PaymentUpdateOne) ClearDeletedAt() *PaymentUpdateOne {
	puo.mutation.ClearDeletedAt()
	return puo
}

// Mutation returns the PaymentMutation object of the builder.
func (puo *PaymentUpdateOne) Mutation() *PaymentMutation {
	return puo.mutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (puo *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Payment entity.
func (puo *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	puo.defaults()
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PaymentUpdateOne) defaults() {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		v := payment.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
}

func (puo *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.EventID(); ok {
		_spec.SetField(payment.FieldEventID, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedEventID(); ok {
		_spec.AddField(payment.FieldEventID, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt, value)
	}
	if value, ok := puo.mutation.PaidBy(); ok {
		_spec.SetField(payment.FieldPaidBy, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedPaidBy(); ok {
		_spec.AddField(payment.FieldPaidBy, field.TypeInt, value)
	}
	if value, ok := puo.mutation.PaidTo(); ok {
		_spec.SetField(payment.FieldPaidTo, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedPaidTo(); ok {
		_spec.AddField(payment.FieldPaidTo, field.TypeInt, value)
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.DeletedAt(); ok {
		_spec.SetField(payment.FieldDeletedAt, field.TypeTime, value)
	}
	if puo.mutation.DeletedAtCleared() {
		_spec.ClearField(payment.FieldDeletedAt, field.TypeTime)
	}
	_node = &Payment{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
